### PR TITLE
Fixed scroll positioning after going back from navigation (#674)

### PR DESCRIPTION
**Pull request by reisfmb**
@poi33 

Tested it in Chrome and Firefox. 

It seems that this strange behavior is only happening in Firefox, and it is happening regardless of the use of the newly added parts... to check that, click on any guide link on [https://developer.enonic.com/](https://developer.enonic.com/) for example, and then go back. You'll get back with the scroll on top.

After some research, I was able to make it work in Firefox too by adding a simple script to the end of the page:

```javascript
if ('scrollRestoration' in history) { history.scrollRestoration = 'auto'; }
```

Idk if that's the best way to solve it, but seems fine to me. What do you think?

### CODE REVIEW

**Comment by sigdestad** [comment]
How strange? Enonic.com is not behaving this way? Must be something in the code that triggers this behavior?

**Comment by reisfmb** [comment]
> How strange? Enonic.com is not behaving this way? Must be something in the code that triggers this behavior?

Enonic.com seems to behave just fine with Firefox. Idk what would trigger that behavior, but I can try to investigate. Was this something that was happening in developer portal even before the release of the new parts? Because atm I can't see a connection of the parts being the ones who are triggering that behavior.

**Comment by poi33** [comment]
Probably a script in main.js that does this. I think you are correct that this is not related to any of the new parts. 
I don't find it a good solution to solve this with inline javascript. We should fix the wierd scrolling, not hide it with forcing scrolling to the last position.

**Review by poi33 — CHANGES_REQUESTED** [review]
🛑Don't force scrolling when we are trying to remove the issue of incorrect scrolling.

**Comment by reisfmb** [comment]
> Probably a script in main.js that does this. I think you are correct that this is not related to any of the new parts. I don't find it a good solution to solve this with inline javascript. We should fix the wierd scrolling, not hide it with forcing scrolling to the last position.

I get your point, but for me the weird scrolling is not forcing it to be automatic, since we always want it to be auto?!

**Comment by reisfmb** [comment]
> Probably a script in main.js that does this. I think you are correct that this is not related to any of the new parts. I don't find it a good solution to solve this with inline javascript. We should fix the wierd scrolling, not hide it with forcing scrolling to the last position.

I understand your point! Here's what I found out... There's a file `tocbot.min.js` which is used in `main.js`. Below is an unminified version of it:

image

And as you can see it forces the `scrollRestoration` to be `manual`.

So it seems that this is the file who overwrites the default `auto` value of `scrollRestoration`.

**Comment by poi33** [comment]
Ah okay i know why its failing now. I'll add the table of content toc to the doc pages only.

**Review by poi33 — APPROVED** [review]

**Pull request merged**
